<!DOCTYPE html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#07151e"><meta name="color-scheme" content="dark"><title>Estiba WMS · Guías de envases</title>@if (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot')))@vite(['resources/css/office.css','resources/css/office-container-dispatches.css','resources/js/office-container-dispatches.js'])@endif</head>
<body>
<section class="office-access" id="officeAccess"><div class="office-access__brand"><div class="office-logo">↗</div><p class="eyebrow">ESTIBA WMS · ENVASES</p><h1>Despacha envases con impacto inmediato y reversible.</h1><p>Esta primera versión emite una guía operacional interna. Confirmar descuenta existencia y carga la cuenta del cliente; anular crea los movimientos de reversa.</p></div><form class="office-access__form" id="officeLoginForm"><div><p class="eyebrow">ACCESO DE OFICINA</p><h2>Ingresar a despacho de envases</h2></div><label><span>Correo</span><input name="email" type="email" required></label><label><span>Contraseña</span><input name="password" type="password" required></label><p class="form-error" id="officeLoginError"></p><button class="primary-button">Ingresar <span>→</span></button></form></section>
<main class="office-app is-hidden" id="officeApp"><header class="office-topbar"><div class="brand-lockup"><span class="office-logo office-logo--small">↗</span><span><strong>ESTIBA WMS</strong><small>DESPACHO ENVASES</small></span></div><nav><a href="/oficina/romana">Romana</a><a href="/oficina/envases/cuenta-corriente">Cuenta envases</a><a class="is-active" href="/oficina/envases/despachos">Guías envases</a><a href="/oficina/accesos">Accesos</a></nav><div class="identity"><span class="identity__avatar" id="officeInitials">GE</span><span><strong id="officeUserName">Usuario</strong><small id="officeUserRole">Despacho</small></span><button id="officeLogoutButton">Cerrar sesión</button></div></header>
<section class="dispatch-workspace"><header class="dispatch-heading"><div><p class="eyebrow">GUÍA OPERACIONAL INTERNA</p><h1>Despacho de envases</h1><p>La propiedad y el movimiento de origen permanecen trazados aunque los envases cambien de cuenta corriente.</p></div><button class="secondary-button" id="reloadButton">↻ Actualizar</button></header>
<section class="panel dispatch-form-panel"><div><p class="eyebrow">NUEVA GUÍA</p><h2>Preparar borrador</h2></div><form id="dispatchForm"><div class="form-grid"><label><span>Cliente destino *</span><select name="cliente_id" required></select></label><label><span>Fecha y hora de salida *</span><input name="salida_at" type="datetime-local" required></label><label><span>Patente</span><input name="patente_camion" maxlength="8"></label><label><span>Conductor</span><input name="nombre_conductor" maxlength="150"></label><label><span>RUT conductor</span><input name="rut_conductor" maxlength="12"></label><label class="wide"><span>Observación</span><textarea name="observacion" maxlength="2000"></textarea></label></div><div class="dispatch-lines" id="dispatchLines"></div><p class="form-error" id="dispatchError"></p><div class="form-actions"><button class="primary-button" type="submit">Crear guía en borrador <span>→</span></button></div></form></section>
<section class="panel"><div class="list-heading"><div><p class="eyebrow">HISTORIAL</p><h2>Guías emitidas</h2></div><span id="guideCount">0 guías</span></div><div class="guide-list" id="guideList"></div></section></section></main>
<div class="loading is-hidden" id="officeLoading"><span></span><strong id="officeLoadingText">Procesando…</strong></div><div class="toast-region" id="officeToasts"></div>
</body></html>
